/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.kaoriya.playground.duckdb;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testMain() throws Exception {
        App.main(null);
    }
}
