/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.kaoriya.playground.duckdb;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testDuckDBBasic() throws Exception {
        var app = new App();
        app.duckdbBasic();
    }

    @Test
    public void testSQLiteBasic() throws Exception {
        var app = new App();
        app.sqliteBasic();
    }
}
